import { Metadata } from 'next';
import { Inconsolata, Karla, Raleway } from 'next/font/google';
import { DesktopHeader, MobileHeader } from '../components/Header';
import { Layout } from '../components';
import Fathom from '../components/Fathom';
import '../styles/globals.css';
import '../styles/cobalt2.prism.css';

const karla = Karla({ subsets: ['latin'], variable: '--karla-font' });
const raleway = Raleway({ subsets: ['latin'], variable: '--raleway-font' });
const inconsolata = Inconsolata({
  subsets: ['latin'],
  variable: '--inconsolata-font',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${karla.variable} ${raleway.variable} ${inconsolata.variable} font-body bg-background`}
      >
        <DesktopHeader />
        <MobileHeader />
        <Layout>{children}</Layout>
        <Fathom />
      </body>
    </html>
  );
}
